name: scenario-b-shift-left-webgoat
on: [workflow_dispatch, push, pull_request]

permissions:
  contents: read
  issues: write

jobs:

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: mkdir -p results/secrets
      - continue-on-error: true
        run: |
          docker run --rm -v "$PWD:/src" zricethezav/gitleaks detect \
            --source=/src --no-git \
            --report-format json \
            --report-path /src/results/secrets/gitleaks.json
      - uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: results/secrets/gitleaks.json

  semgrep:
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - uses: actions/checkout@v5
      - run: mkdir -p results/sast
      - continue-on-error: true
        run: |
          docker run --rm -v "$PWD:/src" returntocorp/semgrep:1.75.0 \
            semgrep scan --config=p/ci \
            --json --metrics=off \
            --output=/src/results/sast/semgrep.json
      - uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: results/sast/semgrep.json

  trivy:
    runs-on: ubuntu-latest
    needs: semgrep
    steps:
      - uses: actions/checkout@v5
      - run: mkdir -p results/sca
      - continue-on-error: true
        run: |
          docker run --rm -v "$PWD:/src" aquasec/trivy:0.49.1 \
            fs /src \
            --scanners vuln,misconfig,license \
            --severity LOW,MEDIUM,HIGH,CRITICAL \
            --format json \
            --output /src/results/sca/trivy.json
      - uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: results/sca/trivy.json

  dast:
    runs-on: ubuntu-latest
    needs: trivy
    steps:
      - name: Start WebGoat
        run: docker run -d -p 8080:8080 --name webgoat webgoat/webgoat
      - name: Wait
        run: sleep 30
      - continue-on-error: true
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: http://localhost:8080/WebGoat
          cmd_options: "-a"
          fail_action: false
          artifact_name: zap-report
